var menuJson = [{
    "createdAt"        : 1488119501.517000000,
    "createdBy"        : "system",
    "updatedAt"        : 1488469081.802000000,
    "updatedBy"        : "system",
    "createdUser"      : null,
    "modifiedUser"     : null,
    "menuId"           : 1,
    "menuGrpCd"        : "SYSTEM_MANAGER",
    "menuNm"           : "시스템 관리",
    "multiLanguageJson": {"ko": "시스템 관리", "en": "System Management"},
    "parentId"         : null,
    "level"            : 0,
    "sort"             : 0,
    "progCd"           : null,
    "children"         : [{
        "createdAt"        : 1488119501.530000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.803000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 2,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "공통코드 관리",
        "multiLanguageJson": {"ko": "공통코드 관리", "en": "CommonCode Mgmt"},
        "parentId"         : 1,
        "level"            : 1,
        "sort"             : 0,
        "progCd"           : "system-config-common-code",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.317000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.317000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "system-config-common-code",
            "progNm"      : "공통코드 관리",
            "progPh"      : "/html/system/system-config-common-code.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "Y",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "system-config-common-code",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 2,
        "name"             : "공통코드 관리"
    }, {
        "createdAt"        : 1488119501.536000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.803000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 3,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "프로그램 관리",
        "multiLanguageJson": {"ko": "프로그램 관리", "en": "Program Mgmt"},
        "parentId"         : 1,
        "level"            : 1,
        "sort"             : 1,
        "progCd"           : "system-config-program",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.405000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.405000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "system-config-program",
            "progNm"      : "프로그램 관리",
            "progPh"      : "/html/system/system-config-program.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "system-config-program",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 3,
        "name"             : "프로그램 관리"
    }, {
        "createdAt"        : 1488119501.594000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.803000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 4,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "메뉴 관리",
        "multiLanguageJson": {"ko": "메뉴 관리", "en": "Menu Mgmt"},
        "parentId"         : 1,
        "level"            : 1,
        "sort"             : 2,
        "progCd"           : "system-config-menu",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.323000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.323000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "system-config-menu",
            "progNm"      : "메뉴 관리",
            "progPh"      : "/html/system/system-config-menu.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "system-config-menu",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 4,
        "name"             : "메뉴 관리"
    }, {
        "createdAt"        : 1488119501.602000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.803000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 5,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "사용자 관리",
        "multiLanguageJson": {"ko": "사용자 관리", "en": "User Mgmt"},
        "parentId"         : 1,
        "level"            : 1,
        "sort"             : 3,
        "progCd"           : "system-auth-user",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.310000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.310000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "system-auth-user",
            "progNm"      : "사용자 관리",
            "progPh"      : "/html/system/system-auth-user.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "system-auth-user",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 5,
        "name"             : "사용자 관리"
    }, {
        "createdAt"        : 1488119501.609000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.803000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 6,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "에러로그 관리",
        "multiLanguageJson": {"ko": "에러로그 관리", "en": "ErrorLog Mgmt"},
        "parentId"         : 1,
        "level"            : 1,
        "sort"             : 4,
        "progCd"           : "system-operation-log",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.411000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.411000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "system-operation-log",
            "progNm"      : "에러로그 관리",
            "progPh"      : "/html/system/system-operation-log.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "N",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "system-operation-log",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 6,
        "name"             : "에러로그 관리"
    }],
    "program"          : null,
    "dataStatus"       : "ORIGIN",
    "__deleted__"      : false,
    "__created__"      : false,
    "__modified__"     : false,
    "open"             : false,
    "id"               : 1,
    "name"             : "시스템 관리"
}, {
    "createdAt"        : 1488119501.679000000,
    "createdBy"        : "system",
    "updatedAt"        : 1488469081.803000000,
    "updatedBy"        : "system",
    "createdUser"      : null,
    "modifiedUser"     : null,
    "menuId"           : 7,
    "menuGrpCd"        : "SYSTEM_MANAGER",
    "menuNm"           : "샘플",
    "multiLanguageJson": {"ko": "샘플", "en": "Samples"},
    "parentId"         : null,
    "level"            : 0,
    "sort"             : 1,
    "progCd"           : null,
    "children"         : [{
        "createdAt"        : 1488119501.691000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.803000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 9,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "페이지 구조",
        "multiLanguageJson": {"ko": "페이지 구조", "en": "Page Structure"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 0,
        "progCd"           : "page-structure",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.223000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.223000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "page-structure",
            "progNm"      : "페이지 구조",
            "progPh"      : "/html/_samples/page-structure.html",
            "target"      : "_self",
            "authCheck"   : "N",
            "schAh"       : "N",
            "savAh"       : "N",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "page-structure",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 9,
        "name"             : "페이지 구조"
    }, {
        "createdAt"        : 1488119501.699000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.803000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 10,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "좌우 좌우 레이아웃",
        "multiLanguageJson": {"ko": "좌우 레이아웃", "en": "Left-Right Layout"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 1,
        "progCd"           : "vertical-layout",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.486000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.486000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "vertical-layout",
            "progNm"      : "좌우 레이아웃",
            "progPh"      : "/html/_samples/vertical-layout.html",
            "target"      : "_self",
            "authCheck"   : "N",
            "schAh"       : "N",
            "savAh"       : "N",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "vertical-layout",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 10,
        "name"             : "좌우 좌우 레이아웃"
    }, {
        "createdAt"        : 1488119501.802000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.804000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 11,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "상하 레이아웃",
        "multiLanguageJson": {"ko": "상하 레이아웃", "en": "Top-Bottom Layout"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 2,
        "progCd"           : "horizontal-layout",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.115000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.115000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "horizontal-layout",
            "progNm"      : "상하 레이아웃",
            "progPh"      : "/html/_samples/horizontal-layout.html",
            "target"      : "_self",
            "authCheck"   : "N",
            "schAh"       : "N",
            "savAh"       : "N",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "horizontal-layout",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 11,
        "name"             : "상하 레이아웃"
    }, {
        "createdAt"        : 1488119501.809000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.804000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 12,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "탭 레이아웃",
        "multiLanguageJson": {"ko": "탭 레이아웃", "en": "Tab Layout"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 3,
        "progCd"           : "tab-layout",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.416000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.416000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "tab-layout",
            "progNm"      : "탭 레이아웃",
            "progPh"      : "/html/_samples/tab-layout.html",
            "target"      : "_self",
            "authCheck"   : "N",
            "schAh"       : "N",
            "savAh"       : "N",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "tab-layout",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 12,
        "name"             : "탭 레이아웃"
    }, {
        "createdAt"        : 1488119501.685000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.804000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 8,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "기본 템플릿",
        "multiLanguageJson": {"ko": "기본 템플릿", "en": "Basic Template"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 4,
        "progCd"           : "basic",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119500.989000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119500.989000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "basic",
            "progNm"      : "기본 템플릿",
            "progPh"      : "/html/_samples/basic.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "basic",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 8,
        "name"             : "기본 템플릿"
    }, {
        "createdAt"        : 1488119501.817000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.804000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 13,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "그리드&폼 템플릿",
        "multiLanguageJson": {"ko": "그리드&폼 템플릿", "en": "Grid&Form Template"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 5,
        "progCd"           : "grid-form",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119500.996000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119500.996000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "grid-form",
            "progNm"      : "그리드&폼 템플릿",
            "progPh"      : "/html/_samples/grid-form.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "grid-form",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 13,
        "name"             : "그리드&폼 템플릿"
    }, {
        "createdAt"        : 1488119501.886000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.804000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 14,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "그리드&탭폼 템플릿",
        "multiLanguageJson": {"ko": "그리드&탭폼 템플릿", "en": "Grid&Form with Tab"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 6,
        "progCd"           : "grid-tabform",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.108000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.108000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "grid-tabform",
            "progNm"      : "그리드&폼탭 템플릿",
            "progPh"      : "/html/_samples/grid-tabform.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "grid-tabform",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 14,
        "name"             : "그리드&탭폼 템플릿"
    }, {
        "createdAt"        : 1488119501.893000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.804000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 15,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "그리드&모달 템플릿",
        "multiLanguageJson": {"ko": "그리드&모달 템플릿", "en": "Grid&Modal Template"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 7,
        "progCd"           : "grid-modal",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119501.101000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119501.101000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "grid-modal",
            "progNm"      : "그리드&모달 템플릿",
            "progPh"      : "/html/_samples/grid-modal.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "grid-modal",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 15,
        "name"             : "그리드&모달 템플릿"
    }, {
        "createdAt"        : 1488119501.900000000,
        "createdBy"        : "system",
        "updatedAt"        : 1488469081.804000000,
        "updatedBy"        : "system",
        "createdUser"      : null,
        "modifiedUser"     : null,
        "menuId"           : 16,
        "menuGrpCd"        : "SYSTEM_MANAGER",
        "menuNm"           : "UI 템플릿",
        "multiLanguageJson": {"ko": "UI 템플릿", "en": "UI Template"},
        "parentId"         : 7,
        "level"            : 1,
        "sort"             : 8,
        "progCd"           : "ax5ui-sample",
        "children"         : [],
        "program"          : {
            "createdAt"   : 1488119500.965000000,
            "createdBy"   : "system",
            "updatedAt"   : 1488119500.965000000,
            "updatedBy"   : "system",
            "createdUser" : null,
            "modifiedUser": null,
            "progCd"      : "ax5ui-sample",
            "progNm"      : "UI 템플릿",
            "progPh"      : "/html/_samples/ax5ui-sample.html",
            "target"      : "_self",
            "authCheck"   : "Y",
            "schAh"       : "Y",
            "savAh"       : "Y",
            "exlAh"       : "N",
            "delAh"       : "N",
            "fn1Ah"       : "N",
            "fn2Ah"       : "N",
            "fn3Ah"       : "N",
            "fn4Ah"       : "N",
            "fn5Ah"       : "N",
            "remark"      : null,
            "id"          : "ax5ui-sample",
            "dataStatus"  : "ORIGIN",
            "__deleted__" : false,
            "__created__" : false,
            "__modified__": false
        },
        "dataStatus"       : "ORIGIN",
        "__deleted__"      : false,
        "__created__"      : false,
        "__modified__"     : false,
        "open"             : false,
        "id"               : 16,
        "name"             : "UI 템플릿"
    }],
    "program"          : null,
    "dataStatus"       : "ORIGIN",
    "__deleted__"      : false,
    "__created__"      : false,
    "__modified__"     : false,
    "open"             : false,
    "id"               : 7,
    "name"             : "샘플"
}]

var commonCodeJson = {
    "DEL_YN"     : [{
        "createdAt"   : 1488119502.188000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.188000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "DEL_YN",
        "groupNm"     : "삭제여부",
        "code"        : "N",
        "name"        : "미삭제",
        "sort"        : 1,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "DEL_YN", "code": "N"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.441000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.441000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "DEL_YN",
        "groupNm"     : "삭제여부",
        "code"        : "Y",
        "name"        : "삭제",
        "sort"        : 2,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "DEL_YN", "code": "Y"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }],
    "USE_YN"     : [{
        "createdAt"   : 1488119502.447000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.447000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "USE_YN",
        "groupNm"     : "사용여부",
        "code"        : "Y",
        "name"        : "사용",
        "sort"        : 1,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "USE_YN", "code": "Y"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.272000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.272000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "USE_YN",
        "groupNm"     : "사용여부",
        "code"        : "N",
        "name"        : "사용안함",
        "sort"        : 2,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "USE_YN", "code": "N"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }],
    "LOCALE"     : [{
        "createdAt"   : 1488119502.182000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.182000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "LOCALE",
        "groupNm"     : "로케일",
        "code"        : "ko_KR",
        "name"        : "대한민국",
        "sort"        : 1,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "LOCALE", "code": "ko_KR"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.174000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.174000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "LOCALE",
        "groupNm"     : "로케일",
        "code"        : "en_US",
        "name"        : "미국",
        "sort"        : 2,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "LOCALE", "code": "en_US"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }],
    "USER_STATUS": [{
        "createdAt"   : 1488119502.277000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.277000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "USER_STATUS",
        "groupNm"     : "계정상태",
        "code"        : "NORMAL",
        "name"        : "활성",
        "sort"        : 1,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "USER_STATUS", "code": "NORMAL"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.035000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.035000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "USER_STATUS",
        "groupNm"     : "계정상태",
        "code"        : "ACCOUNT_LOCK",
        "name"        : "잠김",
        "sort"        : 2,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "USER_STATUS", "code": "ACCOUNT_LOCK"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }],
    "AUTH_GROUP" : [{
        "createdAt"   : 1488119502.285000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.285000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "AUTH_GROUP",
        "groupNm"     : "권한그룹",
        "code"        : "S0001",
        "name"        : "시스템관리자 그룹",
        "sort"        : 1,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "AUTH_GROUP", "code": "S0001"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.356000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.356000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "AUTH_GROUP",
        "groupNm"     : "권한그룹",
        "code"        : "S0002",
        "name"        : "사용자 권한그룹",
        "sort"        : 2,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "AUTH_GROUP", "code": "S0002"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }],
    "USER_ROLE"  : [{
        "createdAt"   : 1488119502.140000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.140000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "USER_ROLE",
        "groupNm"     : "사용자 롤",
        "code"        : "ASP_ACCESS",
        "name"        : "관리시스템 접근 롤",
        "sort"        : 1,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "USER_ROLE", "code": "ASP_ACCESS"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.369000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.369000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "USER_ROLE",
        "groupNm"     : "사용자 롤",
        "code"        : "SYSTEM_MANAGER",
        "name"        : "시스템 관리자 롤",
        "sort"        : 2,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "USER_ROLE", "code": "SYSTEM_MANAGER"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.147000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.147000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "USER_ROLE",
        "groupNm"     : "사용자 롤",
        "code"        : "ASP_MANAGER",
        "name"        : "일반괸리자 롤",
        "sort"        : 3,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "USER_ROLE", "code": "ASP_MANAGER"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.133000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.133000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "USER_ROLE",
        "groupNm"     : "사용자 롤",
        "code"        : "API",
        "name"        : "API 접근 롤",
        "sort"        : 6,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "USER_ROLE", "code": "API"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }],
    "MENU_GROUP" : [{
        "createdAt"   : 1488119502.363000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.363000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "MENU_GROUP",
        "groupNm"     : "메뉴그룹",
        "code"        : "SYSTEM_MANAGER",
        "name"        : "시스템 관리자 그룹",
        "sort"        : 1,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "MENU_GROUP", "code": "SYSTEM_MANAGER"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }, {
        "createdAt"   : 1488119502.435000000,
        "createdBy"   : "system",
        "updatedAt"   : 1488119502.435000000,
        "updatedBy"   : "system",
        "createdUser" : null,
        "modifiedUser": null,
        "groupCd"     : "MENU_GROUP",
        "groupNm"     : "메뉴그룹",
        "code"        : "USER",
        "name"        : "사용자 그룹",
        "sort"        : 2,
        "data1"       : null,
        "data2"       : null,
        "data3"       : null,
        "data4"       : null,
        "data5"       : null,
        "remark"      : null,
        "useYn"       : "Y",
        "id"          : {"groupCd": "MENU_GROUP", "code": "USER"},
        "dataStatus"  : "ORIGIN",
        "__deleted__" : false,
        "__created__" : false,
        "__modified__": false
    }]
};


var scriptSession = {
    "userCd"        : "system",
    "userNm"        : "시스템 관리자",
    "locale"        : "ko_KR",
    "timeZone"      : "Asia/Seoul",
    "dateFormat"    : "YYYY-MM-DD",
    "login"         : true,
    "details"       : {"language": "en"},
    "dateTimeFormat": "YYYY-MM-DD HH:mm:ss",
    "timeFormat"    : "HH:mm:ss"
};