
window.LANG_INSTANCE = (function (json) {
    return new axboot.lang(json);
    })(
        {
        "ax.script.form.validate": "Please enter \"{0}\"",
        "ax.script.deleteconfirm": "Are you sure you want to delete it?",
        "ax.script.toast.test": "\"Toast\" function test",
        "ax.script.form.clearconfirm": "Do you really want to clear the form?",
        "ax.script.requireselect": "No list selected.",
        "ax.script.menu.authgroup.saved": "Menu category saved",
        "ax.script.alert.test": "\"Alert\" function test",
        "ax.script.menu.category.saved": "Menu category saved",
        "ax.script.address.finder.title": "Search",
        "ax.script.menu.save.confirm": "Newly created menu can be saved and edited. Do you want to save it now?",
        "ax.script.onsave": "Saved."
        }
    );
window.LANG = function () {
    return LANG_INSTANCE.get.apply(LANG_INSTANCE, arguments);
}

window.COL_INSTANCE = (function (json) {
    return new axboot.lang(json);
})(
    {"ax.admin.errorlog.build.phase": "Build Phase",
        "ax.admin.sample.language.korean": "Korean",
        "ax.admin.errorlog.host": "Host",
        "ax.admin.user.menu.group": "Menu Group",
        "ax.admin.user.role.name": "Role Description",
        "ax.admin.errorlog.select": "select an error",
        "ax.admin.select": "Select",
        "ax.admin.sample.form.select": "Select",
        "ax.admin.sample.layout.rightpanel": "Right Panel",
        "ax.admin.login": "Login",
        "ax.admin.login.guide.message": "Input your ID and Password",
        "ax.admin.errorlog.message": "Error Message",
        "ax.admin.sample.form.auto.calendar": "Calendar",
        "ax.admin.sample.layout.toppanel": "Top Panel",
        "ax.admin.user.auth.group.setting": "Authentication Group Setting",
        "ax.admin.menu.auth.inquery": "Inquery",
        "ax.admin.program.auth.check.or.not": "Auth Enabled",
        "ax.admin.sample.form.address": "Address",
        "ax.admin.sample.layout.button": "Button",
        "ax.admin.sample.layout.basic.d2": "AXBoot Custom Tag",
        "ax.admin.use.or.not": "Use or not",
        "ax.admin.sample.layout.basic.d1": "Basic Page Structure",
        "ax.admin.menu.program.name": "Program Name",
        "ax.admin.user.password.confirm": "Password Confirm",
        "ax.admin.logout": "Logout",
        "ax.admin.program.name": "Program Name",
        "ax.admin.user.account.status": "Account Status",
        "ax.admin.role.name": "Role",
        "ax.admin.program.code": "Program Code",
        "ax.admin.menu.auth.save": "Save",
        "ax.admin.sample.form.key": "Key *",
        "ax.admin.sample.form.auto.combobox": "Combobox",
        "ax.admin.used": "Used",
        "ax.admin.commoncode.code": "Code",
        "ax.admin.input.search": "Search..",
        "ax.admin.sample.form.etc4": "Account Status",
        "ax.admin.sample.form.etc5": "Description",
        "ax.admin.sample.form.etc1": "ETC1",
        "ax.admin.program.auth.excel": "Excel",
        "ax.admin.sample.form.etc2": "ETC2",
        "ax.admin.menu.auth.apply": "Use Auth",
        "ax.admin.sample.form.etc3": "Use or not",
        "ax.admin.sample.modal.button.search": "Search",
        "ax.admin.sample.language.english": "English",
        "ax.admin.remark": "Remark",
        "ax.admin.commoncode.group.name": "Group Name",
        "ax.admin.inquery": "Inquery",
        "ax.admin.form.validate": "Input the {0}.",
        "ax.admin.sample.modal.button.choice": "Choose",
        "ax.admin.sample.layout.bottompanel": "Buttom Panel",
        "ax.admin.menu.auth.delete": "Delete",
        "ax.admin.locale": "Language",
        "ax.admin.user.menu.group.setting": "Menu Group Setting",
        "ax.admin.user.information": "User Information",
        "ax.admin.sample.form.period": "Period",
        "ax.admin.id": "ID",
        "ax.admin.sample.layout.tabpanel": "Tab Layout Code",
        "ax.admin.user.hp": "Mobile",
        "ax.admin.commoncode.data2": "Data2",
        "ax.admin.commoncode.data3": "Data3",
        "ax.admin.commoncode.data4": "Data4",
        "ax.admin.user.password": "Password",
        "ax.admin.errorlog.id": "ID",
        "ax.admin.user.email": "E-Mail",
        "ax.admin.add": "Add",
        "ax.admin.home": "Home",
        "ax.admin.menu.auth.group.setting": "Authentication Group Setting",
        "ax.admin.commoncode.data1": "Data1",
        "ax.admin.save": "Save",
        "ax.admin.user.language": "Language",
        "ax.admin.sample.modal.button.close": "Close",
        "ax.admin.role.code": "Role Code",
        "ax.admin.user.title": "User List",
        "ax.admin.menu.title": "Menu List",
        "ax.admin.program.auth.delete": "Delete",
        "ax.admin.sample.form.picker": "Picker",
        "ax.admin.program.title": "Program List",
        "ax.admin.errorlog.at": "Occured At",
        "ax.admin.user.id": "ID",
        "ax.admin.delete.all": "Delete All",
        "ax.admin.errorlog.header.info": "Request Header Information",
        "ax.admin.sample.child.list": "Sub Data List",
        "ax.admin.sample.form.code": "Code",
        "ax.admin.delete": "Delete",
        "ax.admin.sort": "Sort",
        "ax.admin.desc": "Description",
        "ax.admin.button": "Button",
        "ax.admin.menu.group": "Menu Group",
        "ax.admin.commoncode.name": "value",
        "ax.admin.name": "Name",
        "ax.admin.errorlog.user.info": "Request User Information",
        "ax.admin.menu.name.lang.multi": "Multi language",
        "ax.admin.menu.form.d1": "Select the menu on the left.",
        "ax.admin.menu.auth.group.code": "Auth Group Code",
        "ax.admin.sample.layout.leftpanel": "Left Panel",
        "ax.admin.user.role.code": "Role Code",
        "ax.admin.login.status.message": "{0}",
        "ax.admin.program.auth.inquery": "Inquery",
        "ax.admin.commoncode.group.code": "Group Code",
        "ax.admin.sample.parent.information": "Detail Information",
        "ax.admin.not.used": "Not Used",
        "ax.admin.find.password": "Find Password",
        "ax.admin.user.name": "User Name",
        "ax.admin.menu.program.code": "Program Code",
        "ax.admin.commoncode.title": "CommonCode List",
        "ax.admin.search": "Search",
        "ax.admin.sample.grid.title": "Program Title",
        "ax.admin.password": "Password",
        "ax.admin.sample.layout.tab.d2": "Tab2",
        "ax.admin.sample.layout.tab.d1": "Tab1",
        "ax.admin.sample.search.condition": "Condition",
        "ax.admin.sample.layout.tab.d4": "Tab4",
        "ax.admin.errorlog.server": "Server",
        "ax.admin.program.progPh": "Path",
        "ax.admin.sample.layout.tab.d3": "Tab3",
        "ax.admin.saved": "Saved",
        "ax.admin.sample.form.show.code.list": "Search Code",
        "ax.admin.commoncode.code.desc": "Description",
        "ax.admin.menu.auth.excel": "Excel",
        "ax.admin.errorlog.parameter.info": "Request Parameter Information",
        "ax.admin.cannot.close.home.tab": "Home tab can't be closed",
        "ax.admin.user.role.setting": "Role Setting",
        "ax.admin.sample.modal.title": "Search Code",
        "ax.admin.find.id": "Find ID",
        "ax.admin.user.auth.group": "Auth Group",
        "ax.admin.sample.form.date": "Date",
        "ax.admin.menu.auth.group.name": "Auth Group Name",
        "ax.admin.sample.search.condition2": "Condition2",
        "ax.admin.sample.search.condition1": "Condition1",
        "ax.admin.sample.form.value": "Value",
        "ax.admin.errorlog.system": "System",
        "ax.admin.sample.layout.tab.d5": "Tab5",
        "ax.admin.errorlog.url": "URL",
        "ax.admin.user.password.change": "Change Password",
        "ax.admin.sample.form.auto.complete": "Auto Complete",
        "ax.admin.sample.search.condition3": "Condition3",
        "ax.admin.program.auth.save": "Save",
        "ax.admin.sample.form.find": "Find",
        "ax.admin.menu.program.setting": "Program Setting",
        "ax.admin.sample.parent.list": "Primary Data List",
        "ax.admin.clear": "Clear"
    }
);
window.COL = function () {
    return COL_INSTANCE.get.apply(COL_INSTANCE, arguments);
}